config:
  sem: true
  rgb: false
  file_name: null
  seed: 0
  gpu_id: 3
  file_path: "src/planner"

  cost_map_name: cost_map_geom # use cost_map_sem for semantic cost maps
  env_list: # Expected under data directory
    - forest_s1_high
    - forest_s2
    - forest_s2_high
    - forest_s2_p2
    - forest_s3
  test_env_id: 3
  data_cfg:
    real_world_data: false # rotate loaded images by 180 degrees
    carla: false # Apply carla specific filtering
    max_depth: 15.0
    max_goal_distance: 15.0
    min_goal_distance: 0.5
    distance_scheme:
      1: 0.2
      3: 0.35
      5: 0.25
      7.5: 0.15
      10: 0.05
    obs_cost_height: 1.5
    fov_scale: 1.0
    depth_scale: 1000.0 
  num_workers: 16
  load_in_ram: false

  fear_ahead_dist: 5.0
  w_obs: 0.5
  w_height: 1.0
  w_motion: 1.5
  w_goal: 4.0
  obstacle_thread: 1.0

  img_input_size: 
    - 360
    - 640
  in_channel: 16 
  knodes: 5 
  pre_train_sem: true
  pre_train_cfg: m2f_model/coco/panoptic/maskformer2_R50_bs16_50ep.yaml
  pre_train_weights: m2f_model/coco/panoptic/model_final_94dc52.pkl
  pre_train_freeze: true
  decoder_small: false
  freeze_layers: 5 # 0 means no freeze, 5 freezes all layers

  resume: true
  epochs: 500
  batch_size: 64
  checkpoint_interval: 0
  hierarchical: false
  hierarchical_step: 50
  hierarchical_front_step_ratio: 0.02
  hierarchical_back_step_ratio: 0.01

  lr: 0.001
  factor: 0.5
  min_lr: 0.00001
  patience: 5
  optimizer: sgd
  momentum: 0.1
  w_decay: 0.0001

  camera_tilt: 0.0 # TODO: Update when recording data with camera tilted
  n_visualize: 15

  # wb_project: VIPlanner
  # wb_entity: viplanner
  # wb_api_key: null
