/**:
  ros__parameters:
    main_freq: 5
    verbose: false

    model_save: "/workspaces/drone_ws/perception_planning/ros_ws/viplanner_ros2/models/2026-05-19_07-36-47"

    depth_topic: /drone_1/depth
    depth_width: 640
    depth_height: 360
    rgb_topic: /drone_1/cam/compressed
    rgb_width: 640
    rgb_height: 360
    rgb_compressed: true
    goal_topic: /way_point
    path_topic: /drone_1/path_follow

    robot_id: d1_base_link
    world_id: world
    mount_cam_frame: ""

    depth_uint_type: false
    max_depth: 15.0
    image_flip: false
    conv_dist: 0.5

    m2f_config_path: ""
    m2f_model_path: ""
    m2f_device: cuda:0

    is_fear_act: false
    fear_threshold: 0.7
    buffer_size: 3
    angular_thread: 0.3
    track_dist: 0.5
    joyGoal_scale: 2.5

    subgoal_max_distance: 20.0
    subgoal_update_distance: 7.0
