VIPLANNER_CLASS_COLORS = {
    "sidewalk": [0, 255, 0],
    "crosswalk": [0, 102, 0],
    "floor": [0, 204, 0],
    "stairs": [0, 153, 0],
    "gravel": [204, 255, 0],
    "sand": [153, 204, 0],
    "snow": [204, 102, 0],
    "indoor_soft": [102, 153, 0],
    "terrain": [255, 255, 0],
    "road": [255, 128, 0],
    "person": [255, 0, 0],
    "anymal": [204, 0, 0],
    "vehicle": [153, 0, 0],
    "on_rails": [51, 0, 0],
    "motorcycle": [102, 0, 0],
    "bicycle": [102, 0, 0],
    "building": [127, 0, 255],
    "wall": [102, 0, 204],
    "fence": [76, 0, 153],
    "bridge": [51, 0, 102],
    "pole": [0, 0, 255],
    "traffic_sign": [0, 0, 153],
    "traffic_light": [0, 0, 204],
    "bench": [0, 0, 102],
    "vegetation": [153, 0, 153],
    "water_surface": [204, 0, 204],
    "sky": [102, 0, 51],
    "background": [102, 0, 51],
    "dynamic": [32, 0, 32],
    "static": [0, 0, 0],
    "furniture": [0, 0, 51],
    "door": [153, 153, 0],
    "ceiling": [25, 0, 51],
}

COCO_PANOPTIC_NAMES = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
    "banner",
    "blanket",
    "bridge",
    "cardboard",
    "counter",
    "curtain",
    "door-stuff",
    "floor-wood",
    "flower",
    "fruit",
    "gravel",
    "house",
    "light",
    "mirror-stuff",
    "net",
    "pillow",
    "platform",
    "playingfield",
    "railroad",
    "river",
    "road",
    "roof",
    "sand",
    "sea",
    "shelf",
    "snow",
    "stairs",
    "tent",
    "towel",
    "wall-brick",
    "wall-stone",
    "wall-tile",
    "wall-wood",
    "water-other",
    "window-blind",
    "window-other",
    "tree-merged",
    "fence-merged",
    "ceiling-merged",
    "sky-other-merged",
    "cabinet-merged",
    "table-merged",
    "floor-other-merged",
    "pavement-merged",
    "mountain-merged",
    "grass-merged",
    "dirt-merged",
    "paper-merged",
    "food-other-merged",
    "building-other-merged",
    "rock-merged",
    "wall-other-merged",
    "rug-merged",
]

COCO_TO_VIPLANNER = {
    "road": ["road"],
    "sidewalk": ["pavement-merged"],
    "floor": ["floor-other-merged", "floor-wood", "platform", "playingfield", "rug-merged"],
    "gravel": ["gravel"],
    "stairs": ["stairs"],
    "sand": ["sand"],
    "snow": ["snow"],
    "person": ["person"],
    "anymal": ["bird", "cat", "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe"],
    "vehicle": ["car", "bus", "truck", "boat"],
    "on_rails": ["train", "railroad"],
    "motorcycle": ["motorcycle"],
    "bicycle": ["bicycle"],
    "building": ["building-other-merged", "house", "roof"],
    "wall": ["wall-other-merged", "curtain", "mirror-stuff", "wall-brick", "wall-stone", "wall-tile", "wall-wood"],
    "fence": ["fence-merged"],
    "bridge": ["bridge"],
    "pole": ["fire hydrant", "parking meter"],
    "traffic_sign": ["stop sign"],
    "traffic_light": ["traffic light"],
    "bench": ["bench"],
    "vegetation": ["potted plant", "flower", "tree-merged", "mountain-merged", "rock-merged"],
    "terrain": ["grass-merged", "dirt-merged"],
    "water_surface": ["river", "sea", "water-other"],
    "sky": ["sky-other-merged", "airplane"],
    "static": ["banner", "cardboard", "light", "tent", "unknown"],
    "furniture": ["chair", "couch", "bed", "dining table", "toilet", "clock", "vase", "blanket", "pillow", "shelf", "cabinet", "table-merged", "counter", "tv"],
    "door": ["door-stuff"],
    "ceiling": ["ceiling-merged"],
    "indoor_soft": ["towel"],
}


def map_dataset_classes(dataset_classes):
    id_to_class = {}
    for idx, class_name in enumerate(dataset_classes):
        for viplanner_class, keywords in COCO_TO_VIPLANNER.items():
            if any(keyword in class_name for keyword in keywords):
                id_to_class[idx] = viplanner_class
                break
    return id_to_class
